### ISSUE TITLE
access repository overview from main page

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#73] opened 2017-03-03 08:59 UTC
Hi, maybe it would be worth to exposing repository overviews on the main page, the only ways I found to see it is to click on repository name in search result or navigation to http://localhost:8080/repository/overview/reponame

**Comment by boyter** [comment] 2017-03-04 01:54
Do you mean from the index page? IE a link from http://localhost:8080/ to http://localhost:8080/repository/overview/reponame

If so, funnily enough that was in the original version, but I dropped it because it did not look very nice.

The issue is when someone has 100+ repositories indexed (this happens more then you would think). I think the main issue is that there is a lack of discoverability with this. Perhaps a page that is viewable by all that has these links in it.

**Comment by quasarea** [comment] 2017-03-04 17:07
Exactly, something like repositories page linked from main page, that you can see list of repos on it and pick each to enter its overview

**Comment by quasarea** [comment] 2017-03-06 08:48
also if bare repo list seems to thin, it would be great to have columns like last scanned & last indexed dates (so scanned and change found) there as there is no easy way to say if repo was actually indexed without manually going to its overview now.

**Comment by boyter** [comment] 2017-03-06 08:56
Thats a fair point. A lot of that information is being tracked now which should make it easier to surface in theory.

**Comment by boyter** [comment] 2017-03-07 07:54
So I have added the endpoint http://localhost:8080/repository/list/ which displays the repositories that are currently in the system. It also displays some information such as, Index Status, Last Index Time, Number of Files and the source.

It also updates for most of the data. I will have to add some paging logic to this for those who have hundreds of repositories but I think that it should work.

It is reachable by clicking on a link from the main page, as well as the top right hand navbar. Currently sitting in the refactor branch.

**Comment by boyter** [comment] 2017-03-07 21:38
Merged into master.

**Closed by boyter** 2017-03-07 21:38 UTC
Labels: enhancement
