### ISSUE TITLE
fab is os dependent

### ISSUE THREAD

**Issue by quasarea** [boyter/searchcode-server#95] opened 2017-03-31 08:31 UTC
```
[localhost] local: rm -rf ./release/*
[localhost] local: cp -R ./target/dependency-jars ./release/
[localhost] local: cp ./target/*.jar ./release/
[localhost] local: cp ./searchcode.properties.example ./release/searchcode.properties
[localhost] local: cp ./quartz.properties ./release/quartz.properties
[localhost] local: cp ./searchcode.sqlite.empty ./release/searchcode.sqlite
[localhost] local: cp ./README.md ./release/
[localhost] local: chmod +x ./searchcode-server.sh
[localhost] local: cp ./searchcode-server.sh ./release/
[localhost] local: cp ./searchcode-server.bat ./release/
[localhost] local: mkdir ./release/logs
```

For window builds you could require http://gnuwin32.sourceforge.net/packages/coreutils.htm 
but even then mkdir will fail, so should be replaced.

I thought to make it os independent in script [fabfile.py.txt](https://github.com/boyter/searchcode-server/files/884949/fabfile.py.txt) but this is not utilising fabs local anymore, so maybe rather than that make two versions of each command depending on system? or maybe fab has some file manipulation mechanics in it?

**Comment by boyter** [comment] 2017-04-03 07:00
I have to wonder if its worth investing too much time in this. To be honest that build process is more for me to produce a build. I guess it may be useful for those wanting to make reproducible builds on Windows, but I have to wonder how many people would use it.

**Comment by quasarea** [comment] 2017-04-10 13:26
Found some net on my holidays ;p It's fine if you don't see a point in fixing that. Surely in such case it should be mentioned :). I have not played with fab before, but what I would do if its not supporting os independent build is:
a) check the os and feedback if not supported
b) check the os and run os specific fabrication process, so I could i.e. accommodate windows build along, but you don't have to be bothered by it at all.

**Comment by boyter** [comment] 2017-04-10 22:17
I think that adding a note that builds are Unix dependant is probably the best option. I do some testing on Windows (check that it builds and tests run) but I am not going to bother spinning a server up for CI for it or to do the actual builds.

TODO - Add nots about this into README and fab file.

**Comment by boyter** [comment] 2017-04-12 08:06
Have added messaging in README and Fab file (if running under Windows) to point this out. Currently the CI system builds using Linux so I think this acceptable for the moment. Windows support is best effort at the moment.

**Comment by quasarea** [comment] 2017-05-15 11:13
one minor fix here would be to replace `local('mkdir ./release/logs')` with 
```
if not os.path.exists('./release/logs'):
        os.makedirs('./release/logs')
```
in `def _build_package(): ` as you already using this structure there for release folder, but not for release/logs

**Comment by boyter** [comment] 2017-05-16 00:39
Should be fairly easy to implement.

**Comment by quasarea** [comment] 2017-05-16 10:03
some things I can work around using cygwin, left overs are this above (mkdir) and tar, but not found workaround tar yet, possibly it will be something like:
`local('7z -ttar a searchcode-server.tar.gz * -so | 7z -si -tgzip a x.tgz')`
but not sure if its supported on linux then ;)

**Comment by boyter** [comment] 2017-05-16 10:30
Might be tricky. Maybe there is a pure python thing I can use.

I had a look at converting over to pure python but ran into issues with verifying the build because tar was producing a different md5 every time. Rather annoying since it means the package is not reproducible. Something to investigate.

**Comment by quasarea** [comment] 2017-05-18 09:15
but aren't you already doing `local('tar cvzf searchcode-server.tar.gz searchcode-server')` already? 
Does this also yields not valid md5? 
CygWin tar for windows cannot do gz as I can tell, most often it is replaced with 7z as its on all platforms and has tar/gz support, see https://superuser.com/questions/244703/how-can-i-run-the-tar-czf-command-in-windows
I would go with 7z just because it is more fancy

**Comment by boyter** [comment] 2017-05-18 21:04
Interestingly when I run that tar command it produces a different file hash every time. Still tracking that one down.

**Comment by NathanaelA** [comment] 2017-06-15 06:11
Tar includes its own time stamps in it.  Each tar produced the header will cause the hash to be different.  ;-)    See: https://www.gnu.org/software/tar/manual/html_node/Standard.html

**Comment by boyter** [comment] 2017-06-15 07:25
Indeed. https://stackoverflow.com/questions/36464358/why-do-the-md5-hashes-of-two-tarballs-of-the-same-file-differ I found that the other day when working on this again.

**Comment by boyter** [comment] 2018-02-06 08:43
Starting to think this is less of an issue these days with the WSL working so well. Heck I have been using it to develop searchcode-server without an issues. Going to resolve the tar issue above then close this down as I think there is no need to solve it anymore.

**Comment by boyter** [comment] 2018-02-06 21:32
Ok even with the tar issue resolved it seems maven still produces un-producible builds. Sigh. Going to close anyway.

**Closed by boyter** 2018-02-06 21:32 UTC
